[build]
    publish = "dist"
    command = "npm run build"

[dev]
    command = "npm run dev"
    port = 8888

[functions]
    directory = "netlify/functions"

[redirects]
    [[redirects]]
        from = "/*"
        to = "marballin-promo-website/index.html"
        status = 200